lk/Account/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Account.Models;
using Account.DAO;
using Account.Security;

namespace Account.Controllers
{
    [Authorize]
    [ValidateInput(false)]
    public class NewsController : SecureController
    {
        [AllowAnonymous]
        public ActionResult Index(string year, string month)
        {
            if (year == null)
            {
                year = DateTime.Now.Year.ToString();
            }
            DateTime date1 = new DateTime();
            
            if (month != null) date1 = new DateTime(Convert.ToInt32(year), Convert.ToInt32(month), 01);
            else date1 = new DateTime(Convert.ToInt32(year), 01, 01);
            
            var news = NewsService.GetAll(
                year,
                month,
                date1,
                null,
                "DatePosted",
                "desc"
            );
            if (Session["NewsTiming"] == null)
            {
                var timing = new Dictionary<int, List<int>>();
                foreach (var rec in NewsService.GetTiming()) {
                    if (!timing.ContainsKey(rec.Year)) {
                        timing.Add(rec.Year, new List<int>());
                    }
                    if (!timing[rec.Year].Contains(rec.Month)) {
                        timing[rec.Year].Add(rec.Month);
                    }
                }
                Session["NewsTiming"] = timing;
            }
            return PartialView(news);
        }

        public ActionResult Manage(FilterTableModel<NewsModel, News> table)
        {
            if (!User.Account.IsAdmin)
                throw new HttpException(403, "Доступ запрещен");

            InitNewsTable(table);
            return View(table);
        }

        [HttpGet]
        [AllowAdminOnly]
        public ActionResult Add()
        {
            return View(new NewsModel());
        }

        [HttpPost]
        [AllowAdminOnly]
        public ActionResult Add(NewsModel m)
        {
            NewsService.Add(User.Account.ID, m.Body);
            return RedirectToAction("Manage");
        }

        [HttpGet]
        [AllowAdminOnly]
        public ActionResult Edit(string id)
        {
            var news = new NewsModel();
            news.From(NewsService.Get(id));
            return View(news);
        }

        [HttpPost]
        [AllowAdminOnly]
        public ActionResult Edit(NewsModel m)
        {
            try
            {
                NewsService.Update(
                    m.ID,
                    User.Account.ID,
                    m.Body
                );
                return RedirectToAction("Manage");
            }
            catch (ArgumentException aex)
            {
                throw new HttpException(404, aex.Message);
            }
        }

        [HttpPost]
        public ActionResult Remove(int id)
        {
            NewsService.Delete(id);
            return RedirectToAction("Manage");
        }

        public static void InitNewsTable(FilterTableModel<NewsModel, News> table)
        {
            if (table.DataModel == null)
            {
                table.DataModel = new NewsModel();
                table.SortingField = "DatePosted";
                table.SortingType = "desc";
            }
            if (table.DataList == null)
                table.DataList = new PagedList<News>();

            table.DataList.DataQuery = NewsService.GetAll(
                null,
                null,
                table.DataModel.DatePosted,
                table.DataModel.Body,
                table.SortingField,
                table.SortingType
            );
        }
    }
}

lk/Account/Views/News/Add.cshtml
@model Account.Models.NewsModel
@{
    ViewBag.Title = "Добавление новости - Федеральная Служба по Финансовым Рынкам";
}

<h2>Добавление новой новости</h2>

<div class="register-form dbi">
    @using(Html.BeginForm())
    {
    @Html.AntiForgeryToken();
    <table class="table-layout ">
        <colgroup><col style="width: 250px"/>
        </colgroup><tbody>
            <tr>
                <td class="tar">@Html.TextAreaFor(m => m.Body)</td>
            </tr>
            <tr>
                <td class="tar"><input class="btn" type="submit" value="Добавить новость" /></td>
            </tr>
        </tbody>
    </table>
    }
</div>

lk/Account/Views/News/Edit.cshtml
@model Account.Models.NewsModel
@{
    ViewBag.Title = "Редактирование новости - Федеральная Служба по Финансовым Рынкам";
}

<h2>Редактирование новости</h2>

<div class="register-form dbi">
    @using(Html.BeginForm())
    {
    @Html.AntiForgeryToken();
    <table class="table-layout ">
        <colgroup><col style="width: 250px">
        </colgroup><tbody>
            <tr>
                <td class="tar">@Html.TextAreaFor(m => m.Body)</td>
            </tr>
            <tr>
                <td class="tar"><input class="btn" type="submit" value="Сохранить" /></td>
            </tr>
        </tbody>
    </table>
    }
</div>

lk/Account/Views/News/Index.cshtml
@model IEnumerable<Account.DAO.News>
@{
    var months = new Dictionary<int, string> {
        {1, "Январь"},
        {2, "Февраль"},
        {3, "Март"},
        {4, "Апрель"},
        {5, "Май"},
        {6, "Июнь"},
        {7, "Июль"},
        {8, "Август"},
        {9, "Сентябрь"},
        {10, "Октябрь"},
        {11, "Ноябрь"},
        {12, "Декабрь"}
    };
    var timing = (Dictionary<int, List<int>>)Session["NewsTiming"];
}

<div class="news">
    <h2 class="news"><a href="/">Новости</a></h2>

    <div class="clear"></div>

    @foreach (var n in Model) {
        var body = new HtmlString(n.Body);

        <article class="news-item">
            <span class="date"><b>@n.DatePosted.ToShortDateString()</b></span>
            <p>@Html.Raw(body)</p>
        </article>
    }

</div>

<!-- YEARS -->
<div class="years">
    <ul>
        @foreach (var item in timing.OrderByDescending(p => p.Key)) {
            <li><a href="#" onclick="showNews(@item.Key)">@item.Key</a>
            <ul>
            @foreach (var month in item.Value.OrderByDescending(m => m)) {
                <li><a href="#" onclick="showNews(@item.Key, @month)">@months[month]</a></li>
            }
            </ul></li>
        }
</div>

lk/Account/Views/News/Manage.cshtml
@model Account.Models.FilterTableModel<Account.Models.NewsModel, Account.DAO.News>
@using Account.Helpers

@{
    ViewBag.Title = "Управление новостями - Федеральная Служба по Финансовым Рынкам";
}

<div class="table-container">
    <form method="post">
        @Html.HiddenFor(m => m.DataList.Page, new { Class="Page-value" })
        @Html.HiddenFor(m => m.DataList.PageSize, new { Class = "PageSize-value" })
        @Html.HiddenFor(m => m.SortingField, new { Class = "SortingField-value" })
        @Html.HiddenFor(m => m.SortingType, new { Class = "SortingType-value" })
        <div id="reports">
            @FilterTableHelper.FilterTable(Model)
            @if (Model.DataList.DataQuery.Count() == 0)
            {
                <div style="width: 300px; margin: 0 auto;">Новостей нет</div>
            }
        </div>
    </form>
</div>

@FilterTableHelper.FilterTablePaging(Model)

@section scripts
{
    @Scripts.Render("~/bundles/jqueryui")

    <script>
        $(document).ready(function () {
            $('.date').parent().parent().addClass('date');
        });

    function confirmDelete(id) {
        result = confirm("Вы уверены что хотите удалить выбранную новость?")
        if (result) {
            $.post(
                '@Url.Action("Remove", "News")',
                { 'id': id, 'returnUrl': '@Request.Url.AbsoluteUri' },
                function (data) {
                    window.location.reload();
                }
            );
        }
        return result;
    }

    function setSorting(e) {
            $e = $(e);
            $('.SortingField-value').val($e.attr('id'));
            if ($e.hasClass('desc'))
                $('.SortingType-value').val('asc');
            else
                $('.SortingType-value').val('desc');
        }

        function setSize(e) {
            $e = $(e);
            $('.PageSize-value').val($e.text());
            $('.Page-value').val(0);
        }

        function goBack() {
            $('.Page-value').val(parseInt($('.Page-value').val()) - 1);
        }

        function goNext() {
            $('.Page-value').val(parseInt($('.Page-value').val()) + 1);
        }

        function goTo(page) {
            $('.Page-value').val(parseInt(page) - 1);
        }

        function clearFilters(filter) {
            if (!filter)
                $('.filter-container input').val('');
            else
                $('#' + filter).val('');
        }
    </script>
}