lk/Account.Monitoring/Controllers/DownloadController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Account.DAO;
using Account.Tools;
using ICSharpCode.SharpZipLib.Zip;

namespace Monitoring.Controllers
{
    public class DownloadController : Controller
    {
        public ActionResult Package(string id)
        {            
            Package p = PackageService.GetPackage(int.Parse(id));

            if (!p.Name.EndsWith(".zip"))
            {
                p.Name = p.Name + ".zip";
            }
            Blob blob = PackageService.GetBlob(p.BlobID);
            return File(blob.Body, "application/zip", p.Name);
        }

        public ActionResult Report(string id)
        {           
            return GetFile(id, true);
        }

        public ActionResult Signature(string id)
        {
            return GetFile(id, false);
        }

        [HttpPost]
        public ActionResult DwonloadReports(string ids)
        {
            if (ids == null )
                return null;
            string[] ids_array = ids.Split(',');
            if (ids_array.Length == 0)
                return null;
            byte[] body = null;
            using (var m = new MemoryStream())
            {
                using (var s = new ZipOutputStream(m))
                {
                    foreach (var id in ids_array)
                    {
                        try
                        {
                            var file = GetReport(id.ToString());
                            var bodyEntry = new ZipEntry(file.FileDownloadName);
                            s.PutNextEntry(bodyEntry);
                            s.Write(file.FileContents, 0, file.FileContents.Length);
                        }
                        catch
                        {
                            //при ошибке просто игнорируем
                        }
                    }
                    body = m.GetBuffer();
                }
            }
            return File(body, "application/zip", "reports.zip");

        }

        FileContentResult GetReport(string id)
        {
            Package p = PackageService.GetPackage(int.Parse(id));
            
            if (p.IsImported == true)
            {
                ReportInfo rep = PackageService.GetReportInfo(p.ID);
                string filename = string.Empty;
                filename = MailStoreHelper.GetAbsoluteFileName(rep.DocumentUrl);
                return File(System.IO.File.ReadAllBytes(filename), "application/text", id + ".zip");
            }
            else
            {
                Blob blob = PackageService.GetBlob(p.BlobID);
                IReportPackage package = ReportPackageManager.Load("report.zip", blob.Body);
                return File(package.ReportBody, "application/text", id + ".xtdd");
            }
        }

        public FileContentResult GetFile(string id,bool report)
        {
            Package p = PackageService.GetPackage(int.Parse(id));
            if (p.IsImported == true)
            {
                ReportInfo rep = PackageService.GetReportInfo(p.ID);
                string filename = string.Empty;
                if (report)
                {
                    filename = MailStoreHelper.GetAbsoluteFileName(rep.DocumentUrl);
                }
                else
                {
                    filename = MailStoreHelper.GetAbsoluteFileName(rep.DocumentSignUrl);
                }
                string name = Path.GetFileName(filename);
                if (!name.EndsWith(".zip"))
                {
                    name = name + ".zip";
                }
                return File(System.IO.File.ReadAllBytes(filename), "application/text", name);
            }
            else
            {
                Blob blob = PackageService.GetBlob(p.BlobID);
                IReportPackage package = ReportPackageManager.Load("report.zip", blob.Body);
                if (report)
                {
                    var name = package.ReportFileName;
                    if (name.ToLower().EndsWith(".zip"))
                        name = name.Remove(name.Length - 4, 4);
                    if (!name.ToLower().EndsWith(".xtdd"))
                        name = name + ".xtdd";

                    return File(package.ReportBody, "application/text", name);
                }
                else
                {
                    return File(package.ReportSign, "application/text", package.SignFileName);
                }
            }
        }

        public ActionResult MailMessage(int id)
        {
            var mail = MailMessageService.GetMailMessage(id);
            string filename = MailStoreHelper.GetAbsoluteFileName(mail.Url);
            return File(System.IO.File.ReadAllBytes(filename), "application/text", Path.GetFileName(filename));
        }
    }
}

lk/Account.Monitoring/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Script.Serialization;
using System.Configuration;

using Account.DAO;
using Account.Tools;
using Monitoring.Models;
using Monitoring.Security;
using Account.DAO.Models;
using Account.DAO.Services;
using Monitoring.SPOService;
using Account.MailService;
using System.IO;
using Monitoring.Helpers;
//using Progresoft.Accounts.ElectroSignature;

namespace Monitoring.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            if (User != null)
            {
                if (!User.Identity.IsAuthenticated)
                    return RedirectToAction("Login", "Account");
                return RedirectToAction("Statuses");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }            
        }


        [AllowAdminOnly]
        [HttpGet]
        public ActionResult UserMonitoring()
        {
            return View(new UserMonitoringModel());
        }

        [HttpPost]
        [AllowAdminOnly]
        public ActionResult UserMonitoring(UserMonitoringModel model)
        {
            var users = UserMonitoringService.GetStats();
            return PartialView("UserMonitoringPartial", users);
        }

        [HttpPost]
        public ActionResult ActionsUsers(int id)
        {
            var info = UserMonitoringService.GetFullInfo(id);
            return PartialView("_UserEditPartial", info);
        }

        [HttpGet]
        public ActionResult Statuses()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Statuses(DateTime? from, DateTime? to)
        {
            if (!from.HasValue)
                from = DateTime.Parse("01.01.2009");
            if (!to.HasValue)
                to = DateTime.Now;

            var stats = StatusService.GetStats(from.Value, to.Value);
            var model = new List<StatusStats>();
            for (int i = 0; i < (int)PrimaryStatus._LAST_; ++i)
            {
                var s = stats.Find(m => m.PrimaryCode == i) ?? new StatusStats()
                {
                    PrimaryCode = i,
                    Count = 0
                };
                model.Add(s);
            }
            return PartialView("_StatusesPartial", model);
        }

        [HttpGet]
        public ActionResult DateLimit()
        {
            return View(new PackageFilterLimitModel());
        }

        [HttpPost]
        public ActionResult DateLimit(PackageFilterLimitModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (!model.Year.HasValue)
                model.Year = null;
            if (!model.Quarter.HasValue)
                model.Quarter = null;
            if (!model.Month.HasValue)
                model.Month = null;
            List<PackageShortInfo> rows = null;
            switch (model.Period)
            {
                case PackagePeriodType.Year:
                    rows = PackageDateLimitService.GetYearStats((int)model.Year);
                    break;
                case PackagePeriodType.Quarter:
                    rows = PackageDateLimitService.GetQuarterStats((int)model.Year, (int)model.Quarter);
                    break;
                case PackagePeriodType.Month:
                    rows = PackageDateLimitService.GetQuarterStats((int)model.Year, (int)model.Month);
                    break;
            }
            return PartialView("_DateLimitPartial", rows);
        }

        [HttpGet]
        public ActionResult DateLimitList()
        {
            return View(PackageDateLimitService.GetAll());
        }

        [HttpGet]
        public ActionResult DateLimitEdit(int year)
        {
            return View((PackageDateLimitModel)PackageDateLimitService.Get(year));
        }

        [HttpGet]
        public ActionResult DateLimitCreate()
        {
            return View("DateLimitEdit", new PackageDateLimitModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DateLimitCreate(PackageDateLimitModel model)
        {
            if (!ModelState.IsValid)
                return View("DateLimitEdit", model);
            PackageDateLimit p = model.ConvertToDAO();
            PackageDateLimitService.Add(p);
            return RedirectToAction("DateLimitList", "Home");
        }

        [HttpPost]
        public ActionResult DateLimitDelete(int? year)
        {
            PackageDateLimitService.Delete(year);
            return PartialView("_DateLimitListPartial", PackageDateLimitService.GetAll());// RedirectToAction("DateLimitList", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DateLimitEdit(PackageDateLimitModel model)
        {
            if (!ModelState.IsValid)
                return View("DateLimitEdit", model);
            PackageDateLimit p = model.ConvertToDAO();
            PackageDateLimitService.Update(p);
            return RedirectToAction("DateLimitList", "Home");
        }

        [HttpGet]
        public ActionResult Users()
        {
            return View(new UserFilterModel());
        }

        [HttpGet]
        public ActionResult UserRegister()
        {
            return View(new UserFilterModel());
        }

        [HttpPost]
        public ActionResult Users(UserFilterModel model)
        {
            if (!model.from.HasValue)
                model.from = DateTime.Parse("01.01.2009");
            if (!model.to.HasValue)
                model.to = DateTime.Now;
            if (((model.inn == null) || (model.inn.Trim() == "")) &&
                ((model.orgName == null) || (model.orgName.Trim() == "")) &&
                  model.currentStatus == null)
            {
                var users = UserService.GetStats(model.from.Value, model.to.Value);
                return PartialView("_UserPartial", users);
            }
            else
            {
                if (model.inn != null) model.inn = model.inn.Trim();
                if (model.orgName != null) model.orgName = model.orgName.Trim();
                var usercount = UserService.GetCountByInnOrName(model.inn, model.orgName);
                if (usercount != 0)
                {
                    var users = UserService.GetStats(model.from.Value, model.to.Value, model.inn, model.orgName, model.currentStatus);
                    return PartialView("_UserPartial", users);
                }
                else
                {
                    ModelState.AddModelError(
                        "UserFilterModel",
                        "Организация не найдена");
                    var users = UserService.GetStats(model.from.Value, model.to.Value, model.inn);
                    return PartialView("_UserPartial", users);
                }
            }            
        }

        [HttpPost]
        public ActionResult UserRegister(UserFilterModel model)
        {
            if (!model.from.HasValue)
                model.from = DateTime.Parse("01.01.2009");
            if (!model.to.HasValue)
                model.to = DateTime.Now;
            
                var users = UserService.GetStatsRegister(model.from.Value, model.to.Value);
                return PartialView("_UserRegisterPartial", users);
            
        }

        [HttpGet]
        public ActionResult Packages()
        {
            return View(new PackageFilterModel());
        }

        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();            
            return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        public ActionResult Packages(PackageFilterModel model,string orderField)
        {
            if (!model.from.HasValue)
                model.from = DateTime.Parse("01.01.2009");
            if (!model.to.HasValue)
                model.to = DateTime.Now;

            int currentStatusCode = model.Package.CurrentStatusCode.HasValue ? 
                                    model.Package.CurrentStatusCode.Value : -1;
            int initialStatusCode = model.Package.InitialStatusCode.HasValue ?
                                    model.Package.InitialStatusCode.Value : -1;
            try
            {
                var packages = PackageService.GetStats(
                    model.from.Value,
                    model.to.Value,
                    model.Package.ID,
                    model.Package.Name,
                    model.Package.Owner,
                    model.Package.Signature,
                    currentStatusCode,
                    initialStatusCode,
                    model.Report.INN,
                    model.Report.OGRN,
                    model.Report.Model,
                    model.Report.Type,
                    model.Report.OrgType,
                    model.Report.DocType,
                    model.Report.Year,
                    model.Report.Quartal,
                    model.Report.Month,
                    model.Report.Date,
                    orderField
                );
                return PartialView("_PackagesPartial", packages);
            }
            catch (Exception ex)
            {
                Tools.Instance.log.DebugException("Error processing package stats", ex);
                return PartialView("_PackagesPartial");
            }
        }


lk/Account.Monitoring/Views/Home/DateLimit.cshtml
@model Monitoring.Models.PackageFilterLimitModel
@using Account.DAO
@{
    ViewBag.Title = "Нарушения сроков сдачи отчетности";
    var QuarterList = new SelectList(Enum.GetNames(typeof(Account.Tools.Quarter)));
    List<int> yearList = new List<int>();
    for (int y = 2011; y < 2025; y++)
    {
        yearList.Add(y);
    }
}

@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
@Html.AntiForgeryToken()

<div>
    <a href="@Url.Action("DateLimitList", "Home")" >Редактирование контроля сроков </a>
</div>
<div class="clear"></div>
<div class="half left">    
    <div class="filters" >
        <div class="block">
            Тип сдачи отчетности<br/>
            @Html.RadioButtonForEnum(m => m.Period)
        </div>
        <div class="clear"></div>
    </div>    
</div>
<div class="half right">
    <div class="filters" >
        <div class="block">
            Год<br/>
            @Html.DropDownListFor(m => m.Year, new SelectList(yearList))
        </div>
        <div class="clear"></div>
        <div class="block">
            Квартал<br/>
            @Html.DropDownListForEnum(m => m.Quarter)
        </div>
        <div class="clear"></div>
        <div class="block">
            Месяц<br/>
            @Html.DropDownListForEnum(m => m.Month)
        </div>
        <div class="clear"></div>
    </div>
</div>


<div class="block">
    <input type="submit" name="filter" value="Собрать статистику" onclick="return gather('@Url.Action("DateLimit", "Home")');"/>
</div>

<div class="clear"></div>
}
<div class="clear"></div>
<h3>Нарушители</h3>
<div id="stats"></div>

@section scripts {
<script type="text/javascript">
    
    
</script>
}

lk/Account.Monitoring/Views/Home/DateLimitEdit.cshtml
@model PackageDateLimitModel
@using Monitoring.Models
@{
    ViewBag.Title = "Редактирование сроков сдачи отчетности";
}
<div class="register-form dbi">
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
{
@Html.AntiForgeryToken()
    if (Model.Year != null)
    {
        <div><h3><b>Год:</b></h3><span>@Model.Year</span>@Html.HiddenFor(m => m.Year)</div>
    }
    else
    {
        @Html.LabelFor(m => m.Year)<br/>@Html.ValidationMessageFor(m => m.Year)<br />
        @Html.TextBoxFor(m => m.Year)
    }
    <table class="table-layout ">
        <colgroup><col style="width: 250px">
        </colgroup><tbody>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.Quarter1)<br/>@Html.ValidationMessageFor(m => m.Quarter1)</td>
                <td>@Html.TextBoxFor(m => m.Quarter1, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.Quarter2)<br/>@Html.ValidationMessageFor(m => m.Quarter2)</td>
                <td>@Html.TextBoxFor(m => m.Quarter2, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.Quarter3)<br/>@Html.ValidationMessageFor(m => m.Quarter3)</td>
                <td>@Html.TextBoxFor(m => m.Quarter3, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.Quarter4)<br/>@Html.ValidationMessageFor(m => m.Quarter4)</td>
                <td>@Html.TextBoxFor(m => m.Quarter4, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.YearLimit)<br/>@Html.ValidationMessageFor(m => m.YearLimit)</td>
                <td>@Html.TextBoxFor(m => m.YearLimit, new { @class = "date", @maxlength = "10" })</td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.January)<br/>@Html.ValidationMessageFor(m => m.January)</td>
                <td>@Html.TextBoxFor(m => m.January, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.February)<br/>@Html.ValidationMessageFor(m => m.February)</td>
                <td>@Html.TextBoxFor(m => m.February, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.March)<br/>@Html.ValidationMessageFor(m => m.March)</td>
                <td>@Html.TextBoxFor(m => m.March, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.April)<br/>@Html.ValidationMessageFor(m => m.April)</td>
                <td>@Html.TextBoxFor(m => m.April, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.May)<br/>@Html.ValidationMessageFor(m => m.May)</td>
                <td>@Html.TextBoxFor(m => m.May, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.June)<br/>@Html.ValidationMessageFor(m => m.June)</td>
                <td>@Html.TextBoxFor(m => m.June, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.July)<br/>@Html.ValidationMessageFor(m => m.July)</td>
                <td>@Html.TextBoxFor(m => m.July, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.August)<br/>@Html.ValidationMessageFor(m => m.August)</td>
                <td>@Html.TextBoxFor(m => m.August, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.September)<br/>@Html.ValidationMessageFor(m => m.September)</td>
                <td>@Html.TextBoxFor(m => m.September, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.October)<br/>@Html.ValidationMessageFor(m => m.October)</td>
                <td>@Html.TextBoxFor(m => m.October, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td class="tar">@Html.LabelFor(m => m.November)<br/>@Html.ValidationMessageFor(m => m.November)</td>
                <td>@Html.TextBoxFor(m => m.November, new { @class = "date", @maxlength = "10" })</td>
                <td>@Html.LabelFor(m => m.December)<br/>@Html.ValidationMessageFor(m => m.December)</td>
                <td>@Html.TextBoxFor(m => m.December, new { @class = "date", @maxlength = "10" })</td>
            </tr>
            <tr>
                <td></td>
                <td><input class="btn" type="submit" value="Сохранить изменения" onclick="return tryToSubmit()" /></td>
                <td><input class="btn" type="submit" value="Вернуться" onclick="return goBack()" /></td>
            </tr>
        </tbody>
    </table>
    
    
}
</div>
@section scripts
{
    <script type="text/javascript">
        jQuery(function ($) {
            $(".date").mask("99.99.9999");
        });

        function goBack() {
            window.location = '@Url.Action("DateLimitList", "Home")';
            return false;
        }
    </script>
}

lk/Account.Monitoring/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

lk/Account.Monitoring/Views/Home/PackageCompare.cshtml
@model Monitoring.Helpers.CompareHelper.CompareResult
@{
    ViewBag.Title = "Сравнение";
}
@section Header
{
    <style>
        table {
            border-collapse: separate;
            border-spacing: 2px;
            background-color: Black;
        }
        tr 
        {
            background-color: White;
        }
        th
        {
            background-color: #aaa;
            color: White; 
            padding: 10px;
            text-align: center;   
            padding: 10px;
        }
        td
        {
            padding: 10px;
        }
        .currentcol
        {
            background-color: #eee;    
        }
        
    </style>
}

<h2>Сравнение</h2>
<table>
<thead>
<tr>
    <th>Название показателя</th>
    @foreach (var header in Model.ChangesHeaders)
    {
        <th>@Html.Raw(header)</th>    
    }
</tr>
</thead>
<tbody>
@foreach (var change in Model.Changes)
{
    <tr>
        <td>@change.Annotation</td>
        @for (int i = 0; i < change.Values.Count; i++ )
        {
            if (i == 0 && Model.CompareCurrent)
            {
                <td class="currentcol">@change.Values[i]</td>
            }
            else
            {
                <td>@change.Values[i]</td>
            }
        }
    </tr>
}
</tbody>
</table>

lk/Account.Monitoring/Views/Home/PackagesHistoryReport.cshtml
<h3 class="filters-date">Дата сдачи отчетности<span onclick="today()">за сегодня</span><span onclick="week()">за неделю</span><span onclick="month()">за месяц</span><span onclick="infinite()">за все время</span></h3>
<div class="filters">
    <div class="block">
        С<br/>
        <input type="text" id="from" class="date" />
    </div>
    <div class="block">
        По<br/>
        <input type="text" id="to" class="date" />
    </div>
    <div class="block">
        <input type="submit" name="filter" value="Собрать статистику" onclick="return gatherDateRange('@Url.Action("PackagesHistoryReport", "Home")');"/>
    </div>
    <div style="clear: both"></div>
</div>

<h3>Статистика</h3>
<div id="stats"></div>

@section scripts {
<script type="text/javascript">
    function showHistory(inn, type, year, quartal, month, date, report_type) {
        $.ajax(
        {
            url: '@Url.Action("PackagesHistoryByOrganization", "Home")',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(
            {
                INN: inn,
                DocTypeCode: type,
                Year: year,
                Quartal: quartal,
                Month: month,
                Date: date,
                report_type: report_type
            }),
            success: function (data) {
                if (String(data).indexOf("Вход в систему мониторинга СПО - Федеральная Служба по Финансовым Рынкам") != -1) {
                    location.href = '@Url.Action("Packages", "Home")';
                }

                $('#report').html(data);

                $('#report')
                    .attr('title', 'История')
                    .removeClass('report-info')
                    .addClass('report-actions')
                    .dialog({ width: 600, height: 600 });
            }

        });
    }
        
        
</script>
}

lk/Account.Monitoring/Views/Home/Statuses.cshtml
@{
    ViewBag.Title = "Статистика по статусам";
}

<h3 class="filters-date">Дата сдачи отчетности<span onclick="today()">за сегодня</span><span onclick="week()">за неделю</span><span onclick="month()">за месяц</span><span onclick="infinite()">за все время</span></h3>
<div class="filters">
    <div class="block">
        С<br>
        <input type="text" id="from" class="date" />
    </div>
    <div class="block">
        По<br>
        <input type="text" id="to" class="date" />
    </div>
    <div class="block">
        <input type="submit" name="filter" value="Собрать статистику" onclick="return gatherDateRange('@Url.Action("Statuses", "Home")')"/>
    </div>
    <div class="clear"></div>
</div>

<h3>Статистика</h3>
<div id="stats" class="normal"></div>

@section scripts {
<script type="text/javascript">
    

</script>
}

lk/Account.Monitoring/Views/Home/_ReportPartial.cshtml
@model Account.DAO.PackageFullInfo
@{
    var CurrentStatus = new HtmlString(Model.CurrentStatus);
    var InitialStatus = new HtmlString(Model.InitialStatus);
}

<table>
    <tr>
        <td>Логин владельца</td>
        <td>@Model.Owner</td>
    </tr>
    @if (Model.IsImported != true)
    {
    <tr>
        <td>Файл Пакета</td>
        <td><a href="@Url.Action("Package", "Download", new { @id = Model.ID })">скачать</a></td>
    </tr>
    }
    <tr>
        <td>Файл Отчета</td>
        <td><a href="@Url.Action("Report", "Download", new { @id = Model.ID } )">скачать</a></td>
    </tr>
    <tr>
        <td>Файл ЭП</td>
        <td><a href="@Url.Action("Signature", "Download", new { @id = Model.ID } )">скачать</a></td>
    </tr>
    <tr>
        <td>ID</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>Внешний ID</td>
        <td>@Model.ExternalID</td>
    </tr>
    <tr>
        <td>Версия</td>
        <td>@Model.Version</td>
    </tr>
    <tr>
        <td>Модель</td>
        <td>@Model.Model</td>
    </tr>
    <tr>
        <td>Пакет</td>
        <td>@Model.Type</td>
    </tr>
    <tr>
        <td>Тип отчетности</td>
        <td>@Model.DocTypeName</td>
    </tr>
    <tr>
        <td>Тип организации</td>
        <td>@Model.OrgTypeName</td>
    </tr>
    <tr>
        <td>Исходящий номер</td>
        <td>@Model.IncomingNumber</td>
    </tr>
    <tr>
        <td>Исходящая дата</td>
        <td>@Model.IncomingDate</td>
    </tr>
    <tr>
        <td>Номер регистрации</td>
        <td>@Model.SedNumber</td>
    </tr>
    <tr>
        <td>Дата регистрации</td>
        <td>@Model.SedDate</td>
    </tr>
    <tr>
        <td>Краткое наименование компании</td>
        <td>@Model.OrgShortName</td>
    </tr>
    <tr>
        <td>Полное наименование компании</td>
        <td>@Model.OrgFullName</td>
    </tr>
    <tr>
        <td>Адрес</td>
        <td>@Model.Address</td>
    </tr>
    <tr>
        <td>Тема отчета</td>
        <td>@Model.Subject</td>
    </tr>
    <tr>
        <td>ИНН</td>
        <td>@Model.INN</td>
    </tr>
    <tr>
        <td>ОГРН</td>
        <td>@Model.OGRN</td>
    </tr>
    <tr>
        <td>ФИО Подписавшего</td>
        <td>@Model.LastName @Model.FirstName @Model.MiddleName</td>
    </tr>
    <tr>
        <td>Дата</td>
        <td>@Model.Date</td>
    </tr>
    <tr>
        <td>Месяц</td>
        <td>@Model.Month</td>
    </tr>
    <tr>
        <td>Квартал</td>
        <td>@Model.Quartal</td>
    </tr>
    <tr>
        <td>Год</td>
        <td>@Model.Year</td>
    </tr>
    <tr>
        <td>Текущий статус</td>
        <td>@CurrentStatus</td>
    </tr>
    <tr>
        <td>Доп. информация по текущему статусу</td>
        <td>@Model.CurrentStatusException</td>
    </tr>
    <tr>
        <td>Внутренний статус</td>
        <td>@Model.CurrentStatusDetail</td>
    </tr>
    <tr>
        <td>Cтатус проверки ЭП</td>
        <td>@InitialStatus</td>
    </tr>
    <tr>
        <td>Внутренний статус проверки ЭП</td>
        <td>@Model.InitialStatusDetail</td>
    </tr>
    <tr>
        <td colspan="2">Запросы в СЭД</td>
    </tr>
    @foreach (var mail in Model.ToSedMailMessages)
    {
        <tr>
            <td colspan="2"><a href='@Url.Action("MailMessage", "Download", new { @id = mail.ID })'>Subject: @mail.Subject; Date: @mail.CreateAt</a></td>
        </tr>
    }
    <tr>
        <td colspan="2">Ответы СЭД</td>
    </tr>
    @foreach (var mail in Model.FromSedMailMessages)
    {
        <tr>
            <td colspan="2"><a href='@Url.Action("MailMessage", "Download", new { @id = mail.ID })'>Subject: @mail.Subject; Date: @mail.CreateAt</a></td>
        </tr>
    }
</table>

lk/Account.Monitoring/Views/Home/_StatusesPartial.cshtml
@model List<Account.DAO.StatusStats>
@{
    ViewBag.Title = "Сводная статистика";

    int total = 0;
    foreach (var stat in Model)
    {
        total += stat.Count;
    }
}

@if (total > 0)
{
<table>
    <tr style="font-weight: bold">
        <td>Код</td>
        <td>Статус</td>
        <td>Количество</td>
        <td>% от всех</td>
    </tr>
    @foreach (var stat in Model)
    {        
        string percent = string.Format("{0:0.0}", (double)stat.Count * 100 / total);
        var text = new HtmlString(@stat.Status);
        <tr>
            <td>@stat.PrimaryCode</td>
            <td>@text</td>
            <td>@stat.Count</td>
            <td>@percent</td>
        </tr>
    }
    <tr>
        <td style="font-weight: bold"> <br/>Всего</td>
        <td></td>
        <td>@total</td>
        <td></td>
    </tr>
</table>
}
else
{
    <div style="font-weight: bold; margin: 0 auto;">За заданный промежуток времени данные не найдены</div>
}